[1-readme-fixes] Readme updated
wojciechszmelczerczyk/express-notes-app pull request #10
Opened 2022-04-16 10:30 UTC by wojciechszmelczerczyk

## App architecture
-  More info added

## App flow
- I made app flow more talkative

2022-04-16 19:17 UTC, matteocrippa requested changes
Drop specific notes in place where some changes are needed

2022-04-16 19:17 UTC, matteocrippa commented on readme.md
> +cd /path/to/project
trivial, at least add the name of the folder for the proejct, i smell it should be express-notes-app

2022-04-16 19:17 UTC, matteocrippa commented on readme.md
> +[![](https://mermaid.ink/img/pako:eNptkLFqw0AMhl9FaHIgfgEPBdvXoUOhtIUutyg-JT4S37l3uiHEefeqJB5SqkXi14d-SRccomNs8JBoHuHT2AAabdWfPAeBL95toK6fYEn8XTjLAl31rhnat5fNDe5WIM8xZF6gfdAPLJBn5mGsj3xeoK9e_ZBijvt_h
Make more clear the registration flow, there's something i don't get in the retry

2022-04-18 07:55 UTC, wojciechszmelczerczyk commented on readme.md
> +git clone https://github.com/wojciechszmelczerczyk/express-notes-app.git
project url added to project clone readme section

2022-04-18 07:55 UTC, wojciechszmelczerczyk commented on readme.md
> +cd /express-notes-app
replate arbitrary path with project name

2022-04-18 07:57 UTC, wojciechszmelczerczyk commented on readme.md
> +[![](https://mermaid.ink/img/pako:eNpVks9uwjAMxl_FyolJ8AI9bALa8ee63SgHq_FKBE0q1zChlnefSwp0vaT5_LNjf0lrimDJJKZkrA_wneYe9JvvmErXCDHUWNIeZrP3ruZwcZagYLLkxeGp6WDRIv-ToAjMVMjHLZZa9LmwmVypeRsr24kPg7C9C53wF
registration flow updated

2022-04-22 13:07 UTC, matteocrippa approved these changes

2022-04-22 14:56 UTC, merged